version: 2
defaults: &defaults
  docker:
    - image: "circleci/node:14"
  working_directory: ~/data
  resource_class: medium

aliases:
  - &restore_npm_cache
    name: Restoring npm cache
    key: v1-npm-{{ checksum "package-lock.json" }}

  - &save_npm_cache
    name: Saving npm cache
    key: v1-npm-{{ checksum "package-lock.json" }}
    paths:
      - ~/data/node_modules

jobs:
  bundle_dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/data
      - restore_cache: *restore_npm_cache
      - run: npm ci
      - save_cache: *save_npm_cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/data
      - run: npm run lint
  version:
    <<: *defaults
    steps:
      - run: node -v
      - run: npm -v
  types:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/data
      - run: npx tsc --noEmit
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/data
      - run: npm run test -- --runInBand
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/data
      - run:
          name: build
          command: GATSBY_CPU_COUNT=1 CONTEXT=production npm run build
      - run:
          name: integration test
          command: npm run test:integration
  build_with_ssr:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/data
      - run:
          name: build
          command: GATSBY_CPU_COUNT=1 CONTEXT=production SSR_BUILD=enabled npm run build

workflows:
  version: 2
  build:
    jobs:
      - version
      - bundle_dependencies
      - build:
          requires:
            - bundle_dependencies
      - build_with_ssr:
          requires:
            - bundle_dependencies
      - lint:
          requires:
            - bundle_dependencies
      - types:
          requires:
            - bundle_dependencies
      - test:
          requires:
            - bundle_dependencies
