version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: compilation
          command: npx tsc --noEmit
      - run:
          name: test
          command: npm run test
      - run:
          name: build
          command: GATSBY_CPU_COUNT=1 CONTEXT=production npm run build
      - run:
          name: integration test
          command: npm run test:integration
